# Generated by Django 4.2 on 2023-04-24 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(default='matn kiritilmagan', max_length=512)),
                ('title_ru', models.CharField(default='matn kiritilmagan', max_length=512)),
                ('text_uz', models.TextField(default='matn kiritilmagan')),
                ('text_ru', models.TextField(default='matn kiritilmagan')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(default='matn kiritilmagan', max_length=128)),
                ('title_ru', models.CharField(default='matn kiritilmagan', max_length=128)),
                ('text_uz', models.TextField(default='matn kiritilmagan')),
                ('text_ru', models.TextField(default='matn kiritilmagan')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
            options={
                'verbose_name_plural': 'Comments',
            },
        ),
        migrations.CreateModel(
            name='DachaKategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(default='kategoriya kitilmagan', max_length=512)),
                ('name_ru', models.CharField(default='kategoriya kitilmagan', max_length=512)),
            ],
            options={
                'verbose_name_plural': 'Kategorya',
            },
        ),
        migrations.CreateModel(
            name='DachaVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='videos/')),
            ],
            options={
                'verbose_name_plural': 'Dacha_Video',
            },
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='matn kiritilmagan', max_length=128)),
                ('phone', models.CharField(default='matn kiritilmagan', max_length=128)),
            ],
            options={
                'verbose_name_plural': 'Form',
            },
        ),
        migrations.CreateModel(
            name='MijozlarFikrlariAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='audio_files/')),
            ],
            options={
                'verbose_name_plural': 'Mijozlar_Fikri_Audio',
            },
        ),
        migrations.CreateModel(
            name='MijozlarFikrlariImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(upload_to='screenshots/')),
            ],
            options={
                'verbose_name_plural': 'Mijozlar_Fikrlari_ScreenShot',
            },
        ),
        migrations.CreateModel(
            name='QimizOlishZonaDachalari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(default='matn kiritilmagan', max_length=128)),
                ('title_ru', models.CharField(default='matn kiritilmagan', max_length=128)),
                ('cost', models.IntegerField(default=1000000)),
                ('text_uz', models.TextField(default='matn kiritilmagan')),
                ('text_ru', models.TextField(default='текст не введен')),
                ('image', models.ImageField(upload_to='images/')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_uz', to='basic_app.dachakategory')),
            ],
            options={
                'verbose_name_plural': 'Qimiz_Olish_Dacha_Zonalari',
            },
        ),
    ]
