# Generated by Django 4.2 on 2023-04-26 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='text_en',
            field=models.TextField(default='matn kiritilmagan'),
        ),
        migrations.AddField(
            model_name='about',
            name='title_en',
            field=models.CharField(default='matn kiritilmagan', max_length=512),
        ),
        migrations.AddField(
            model_name='comments',
            name='text_en',
            field=models.TextField(default='matn kiritilmagan'),
        ),
        migrations.AddField(
            model_name='comments',
            name='title_en',
            field=models.CharField(default='matn kiritilmagan', max_length=128),
        ),
        migrations.AddField(
            model_name='qimizolishzonadachalari',
            name='text_en',
            field=models.TextField(default='text not entered'),
        ),
        migrations.AddField(
            model_name='qimizolishzonadachalari',
            name='title_en',
            field=models.CharField(default='matn kiritilmagan', max_length=128),
        ),
    ]
